# Generated by Django 3.0.3 on 2020-07-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenizer', '0003_auto_20200714_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='Keywords',
            new_name='keywords',
        ),
    ]
